### ISSUE TITLE
Ruby 2.0 breaks SSL cert verification

### ISSUE THREAD

**Issue by jdigger** [jdigger/git-process#132]
```
/opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::Error::ConnectionFailed)
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:75:in `perform_request'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:38:in `call'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/response.rb:8:in `call'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response/follow_redirects.rb:79:in `perform_with_redirection'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response/follow_redirects.rb:65:in `call'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/response.rb:8:in `call'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/request/encode_json.rb:23:in `call'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/faraday-0.8.9/lib/faraday/connection.rb:118:in `post'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/octokit-1.24.0/lib/octokit/request.rb:64:in `request'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/octokit-1.24.0/lib/octokit/request.rb:29:in `post'
	from /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/octokit-1.24.0/lib/octokit/client/authorizations.rb:55:in `create_authorization'
```

**Comment by jdigger** [comment]
This is fixed in v3.0.0
